export const GamingLibraryData = [
    {
        img: require('../asset/popular-01.jpg'),
        title: "Dota2",
        category: "Sandbox",
        date_added: "24/08/2036",
        hours_played: "634 H 22 Mins",
        download: "Downloaded",
    },
    {
        img: require('../asset/popular-02.jpg'),
        title: "Fortnite",
        category: "Sandbox",
        date_added: "22/06/2036",
        hours_played: "740 H 52 Mins",
        download: "Downloaded",
    },
    {
        img: require('../asset/popular-03.jpg'),
        title: "CS-GO",
        category: "Sandbox",
        date_added: "21/04/2036",
        hours_played: "892 H 14 Mins",
        download: "Downloaded",
    },
    // {
    //     img: require('../asset/popular-04.jpg'),
    //     title: "CS-GO",
    //     titleTow: "Legendary",
    //     valuation: "4.8",
    //     size: "2.3M",
    // },
    // {
    //     img: require('../asset/popular-05.jpg'),
    //     title: "Mini Craft",
    //     titleTow: "Legendary",
    //     valuation: "4.8",
    //     size: "2.3M",
    // },
    // {
    //     img: require('../asset/popular-06.jpg'),
    //     title: "Eagles Fly",
    //     titleTow: "Matrix Games",
    //     valuation: "4.8",
    //     size: "2.3M",
    // },
    // {
    //     img: require('../asset/popular-07.jpg'),
    //     title: "Warface",
    //     titleTow: "Max 3D",
    //     valuation: "4.8",
    //     size: "2.3M",
    // },
    // {
    //     img: require('../asset/popular-08.jpg'),
    //     title: "Warcraft",
    //     titleTow: "Legend",
    //     valuation: "4.8",
    //     size: "2.3M",
    // },
]
