export const StreamsMostData = [
    {
        img: require('../asset/stream-05.jpg'),
        icon: require('../asset/avatar-01.jpg'),
        name:'KenganC',
        title: "Just Talking With Fans",
        watch: "1.2K",
        type: "CS-GO",
    },
    {
        img: require('../asset/stream-06.jpg'),
        icon: require('../asset/avatar-02.jpg'),
        name: "LunaMa",
        title: "CS-GO 36 Hours Live Stream",
        watch: "2K",
        type: "CS-GO",
    },
    {
        img: require('../asset/stream-07.jpg'),
        icon: require('../asset/avatar-03.jpg'),
        name: 'Areluwa',
        title: "Maybe Nathej Allnight Chillin",
        watch: "1.8K",
        type: "CS-GO",
    },
    {
        img: require('../asset/stream-08.jpg'),
        icon: require('../asset/avatar-04.jpg'),
        name: "GangTm",
        title: "Live Streaming Till Morning",
        watch: "1.7K",
        type: "CS-GO",
    },
    {
        img: require('../asset/stream-07.jpg'),
        icon: require('../asset/avatar-01.jpg'),
        name:'KenganC',
        title: "Just Talking With Fans",
        watch: "1.2K",
        type: "CS-GO",
    },
    {
        img: require('../asset/stream-08.jpg'),
        icon: require('../asset/avatar-02.jpg'),
        name: "LunaMa",
        title: "CS-GO 36 Hours Live Stream",
        watch: "2K",
        type: "CS-GO",
    },
    {
        img: require('../asset/stream-05.jpg'),
        icon: require('../asset/avatar-03.jpg'),
        name: 'Areluwa',
        title: "Maybe Nathej Allnight Chillin",
        watch: "1.8K",
        type: "CS-GO",
    },
    {
        img: require('../asset/stream-06.jpg'),
        icon: require('../asset/avatar-04.jpg'),
        name: "GangTm",
        title: "Live Streaming Till Morning",
        watch: "1.7K",
        type: "CS-GO",
    },
]